# .github/actions/my-custom-action/action.yml
name: 'Notify PR Author'
description: 'A custom action to demonstrate how to create one'
inputs:
  my-input:
    description: 'An example input'
    required: true
    default: 'default value'
runs:
  using: 'node20'
  main: 'index.js'