# .github/actions/my-custom-action/action.yml
name: 'Notify PR Author'
description: 'A custom action to demonstrate how to create one'
inputs:
  slack-bot-token:
    description: 'Slack bot token'
    required: true
runs:
  using: 'node20'
  main: 'index.js'